"""The schema must be legal on PostgreSQL, not only on SQLite.

WHY THIS EXISTS
---------------
The system was developed against SQLite and deployed against PostgreSQL. Three classes of defect
made the migration fail outright on the first real PostgreSQL run, and every one of them was
invisible locally because SQLite is permissive in exactly the places PostgreSQL is not:

* **Identifier length.** PostgreSQL's ``NAMEDATALEN`` caps identifiers at 63 characters. SQLite has
  no limit. Eight constraint names generated by the naming convention were 64-93 characters, and
  the migration died on the second revision.
* **Booleans are a real type.** SQLite stores 0/1 in an INTEGER, so ``answered = 1`` and
  ``DEFAULT 0`` on a boolean column are both fine there. PostgreSQL has a genuine boolean and no
  implicit cast, so both are hard errors — ``operator does not exist: boolean = integer``. Sixteen
  predicates were affected across eight modules.
* **Defaults must match their column's type.** The mirror of the above: ``DEFAULT false`` on an
  integer counter fails just as loudly.

None of this could be caught by a test that runs on SQLite — which is every test in this suite. So
these checks read the **metadata** and assert properties that are true or false independently of
which database is connected. They are static, fast, and they would have caught all three.

WHAT THIS DOES NOT DO
---------------------
It does not replace running the migration against a real PostgreSQL server, which is the only way
to prove the triggers install and the partial indexes are genuinely partial. That is done by
``scripts/verify_postgres.py``. This file is the cheap gate that runs on every commit; that script
is the expensive one that runs when a database is available.
"""

from __future__ import annotations

import re

from sqlalchemy import Boolean, Integer, Numeric, SmallInteger

from app.db.metadata import target_metadata

#: PostgreSQL's NAMEDATALEN - 1. Also the limit for MySQL (64) minus nothing, so this is the
#: strictest common bound and the one worth holding to.
POSTGRES_IDENTIFIER_LIMIT = 63


def _boolean_columns() -> dict[str, set[str]]:
    return {
        table.name: {
            column.name for column in table.columns if isinstance(column.type, Boolean)
        }
        for table in target_metadata.sorted_tables
    }


def test_every_identifier_fits_postgresqls_limit() -> None:
    """A name over 63 characters fails ``CREATE TABLE`` on PostgreSQL.

    Checked for constraints and indexes as well as tables and columns, because the naming
    convention composes table, column and referred-table names — which is right for readability and
    is exactly how a name reaches 93 characters.
    """
    offenders: list[str] = []
    for table in target_metadata.sorted_tables:
        candidates: list[tuple[str, str]] = [("table", table.name)]
        candidates += [("column", column.name) for column in table.columns]
        candidates += [
            (type(constraint).__name__, str(constraint.name))
            for constraint in table.constraints
            if constraint.name and not str(constraint.name).startswith("_unnamed_")
        ]
        candidates += [("Index", str(index.name)) for index in table.indexes if index.name]

        for kind, name in candidates:
            if len(name) > POSTGRES_IDENTIFIER_LIMIT:
                offenders.append(f"{table.name}: {kind} {name!r} is {len(name)} characters")

    assert offenders == [], (
        f"PostgreSQL refuses identifiers longer than {POSTGRES_IDENTIFIER_LIMIT} characters, and "
        "SQLAlchemy would silently truncate them to an opaque hashed name. Give the constraint an "
        "explicit shorter name:\n  " + "\n  ".join(offenders)
    )


def test_no_check_constraint_compares_a_boolean_with_an_integer() -> None:
    """``answered = 1`` is valid SQLite and invalid PostgreSQL.

    The portable forms are ``col`` / ``NOT col`` for a truth test and ``col IN (TRUE, FALSE)`` for a
    domain guard — SQLite has folded the TRUE/FALSE keywords to 1/0 since 3.23, so nothing is lost
    there.
    """
    booleans = _boolean_columns()
    offenders: list[str] = []

    for table in target_metadata.sorted_tables:
        columns = booleans.get(table.name, set())
        if not columns:
            continue
        for constraint in table.constraints:
            sqltext = getattr(constraint, "sqltext", None)
            if sqltext is None:
                continue
            text = str(sqltext)
            for column in columns:
                patterns = (
                    rf"\b{re.escape(column)}\s*=\s*[01]\b",
                    rf"\b{re.escape(column)}\s*<>\s*[01]\b",
                    rf"\b{re.escape(column)}\s+IN\s*\(\s*0\s*,\s*1\s*\)",
                )
                if any(re.search(pattern, text, re.IGNORECASE) for pattern in patterns):
                    offenders.append(
                        f"{table.name}.{constraint.name}: boolean {column!r} compared with an "
                        f"integer in {text!r}"
                    )
                    break

    assert offenders == [], (
        "PostgreSQL has a real boolean type and no implicit cast from integer, so these CHECK "
        "constraints would fail the migration:\n  " + "\n  ".join(offenders)
    )


def test_no_server_default_contradicts_its_columns_type() -> None:
    """A boolean column needs ``true``/``false``; a numeric one needs a number.

    Both directions are asserted because both have happened. The first was the original defect;
    the second was introduced while fixing it, by a replacement broad enough to turn an integer
    counter's ``DEFAULT 0`` into ``DEFAULT false``.
    """
    offenders: list[str] = []
    numeric_types = (Integer, SmallInteger, Numeric)

    for table in target_metadata.sorted_tables:
        for column in table.columns:
            default = column.server_default
            if default is None:
                continue
            rendered = str(getattr(default, "arg", default)).strip().strip("'\"").lower()

            if isinstance(column.type, Boolean):
                if rendered in {"0", "1"}:
                    offenders.append(
                        f"{table.name}.{column.name}: boolean column with integer default "
                        f"{rendered!r} — PostgreSQL rejects DEFAULT 0 on a boolean"
                    )
            elif isinstance(column.type, numeric_types) and rendered in {"true", "false"}:
                offenders.append(
                    f"{table.name}.{column.name}: numeric column with boolean default "
                    f"{rendered!r} — PostgreSQL rejects DEFAULT false on an integer"
                )

    assert offenders == [], "server defaults contradict their column types:\n  " + "\n  ".join(
        offenders
    )


def test_no_partial_index_predicate_compares_a_boolean_with_an_integer() -> None:
    """Partial indexes carry their own SQL, and it is dialect-specific by construction.

    Both ``sqlite_where`` and ``postgresql_where`` are declared for these indexes, so the
    PostgreSQL variant has to be valid PostgreSQL — and a boolean/integer comparison in it would
    fail at index creation, after the table already existed.
    """
    booleans = _boolean_columns()
    offenders: list[str] = []

    for table in target_metadata.sorted_tables:
        columns = booleans.get(table.name, set())
        if not columns:
            continue
        for index in table.indexes:
            for dialect in ("sqlite", "postgresql"):
                where = index.dialect_options.get(dialect, {}).get("where")
                if where is None:
                    continue
                text = str(where)
                for column in columns:
                    if re.search(rf"\b{re.escape(column)}\s*=\s*[01]\b", text, re.IGNORECASE):
                        offenders.append(
                            f"{index.name} ({dialect}_where): boolean {column!r} compared with an "
                            f"integer in {text!r}"
                        )

    assert offenders == [], "partial index predicates are not portable:\n  " + "\n  ".join(offenders)


def test_the_migrations_carry_no_over_long_or_split_identifier() -> None:
    """The migration files hold rendered names as literals, which the metadata cannot see.

    Two of the eight over-long names were written across a line continuation —
    ``"fk_..._version_id_" "qc_configuration_versions"`` — so a search for the whole name found
    nothing while the composed identifier was still 93 characters. Both forms are checked.
    """
    from pathlib import Path

    versions = Path(__file__).resolve().parents[1] / "alembic" / "versions"
    prefixes = r"(?:fk|ck|ux|ix|pk|uq)"
    offenders: list[str] = []

    for path in sorted(versions.glob("*.py")):
        text = path.read_text(encoding="utf-8")
        for match in re.finditer(rf'"({prefixes}_[a-z0-9_]+)"', text):
            name = match.group(1)
            if len(name) > POSTGRES_IDENTIFIER_LIMIT:
                offenders.append(f"{path.name}: {name} ({len(name)})")
        # Adjacent string literals that Python concatenates into one identifier.
        for match in re.finditer(
            rf'"({prefixes}_[a-z0-9_]+_)"\s*\n\s*"([a-z0-9_]+)"', text
        ):
            composed = match.group(1) + match.group(2)
            if len(composed) > POSTGRES_IDENTIFIER_LIMIT:
                offenders.append(f"{path.name}: split literal {composed} ({len(composed)})")

    assert offenders == [], (
        "these migration files name identifiers PostgreSQL cannot store:\n  "
        + "\n  ".join(offenders)
    )


def test_the_migrations_carry_no_type_contradicting_default() -> None:
    """The same type/default check, against the migration literals.

    The metadata check above cannot see these: a migration's ``sa.Column(...)`` call is a literal in
    a file, and the column it creates may since have been dropped or altered. It still has to be
    valid at the moment that revision runs.
    """
    from pathlib import Path

    versions = Path(__file__).resolve().parents[1] / "alembic" / "versions"
    offenders: list[str] = []
    default = re.compile(r"server_default=sa\.text\('([^']*)'\)")

    for path in sorted(versions.glob("*.py")):
        for number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
            if "sa.Column(" not in line:
                continue
            match = default.search(line)
            if match is None:
                continue
            value = match.group(1).lower()
            is_boolean = "sa.Boolean()" in line
            is_numeric = any(
                marker in line
                for marker in ("sa.Integer()", "sa.SmallInteger()", "sa.BigInteger()", "sa.Float(")
            )
            if is_boolean and value in {"0", "1"}:
                offenders.append(f"{path.name}:{number} boolean column with DEFAULT {value}")
            if is_numeric and value in {"true", "false"}:
                offenders.append(f"{path.name}:{number} numeric column with DEFAULT {value}")

    assert offenders == [], (
        "these migration literals would fail on PostgreSQL:\n  " + "\n  ".join(offenders)
    )


def test_no_migration_compares_a_boolean_with_an_integer_in_raw_sql() -> None:
    """``WHERE is_correct = 1`` is valid SQLite and invalid PostgreSQL.

    The checks above cover CHECK constraints, server defaults and partial-index predicates — every
    place a boolean/integer comparison can be *declared*. They do not cover raw SQL inside a
    migration body, and that is where one got through: a backfill written and tested against SQLite
    would have failed the first time it ran on PostgreSQL, with the upgrade half-applied.

    A boolean column is tested for truthiness directly (``AND is_correct``) or against
    ``true``/``false``. Never against ``1`` or ``0``.
    """
    from pathlib import Path

    booleans = _boolean_columns()
    every_boolean = {name for names in booleans.values() for name in names}
    offenders: list[str] = []

    versions = Path(__file__).resolve().parents[1] / "alembic" / "versions"
    for path in sorted(versions.glob("*.py")):
        for number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
            stripped = line.strip()
            if stripped.startswith("#") or stripped.startswith("--"):
                continue
            for column in every_boolean:
                for operator in ("=", "!=", "<>"):
                    for value in ("0", "1"):
                        for spacing in (
                            f"{column} {operator} {value}",
                            f"{column}{operator}{value}",
                        ):
                            if spacing in stripped:
                                offenders.append(
                                    f"{path.name}:{number} boolean {column!r} compared with "
                                    f"{value} — PostgreSQL rejects this"
                                )

    assert offenders == [], (
        "a migration compares a boolean column with an integer in raw SQL, which PostgreSQL "
        "rejects with 'operator does not exist: boolean = integer': " + str(sorted(set(offenders)))
    )
