"""Domain contracts: enums, repository records, filters and analytics outputs."""

from app.modules.analytics.domain.analytics import (
    FlagEvaluationResult,
    FlaggedQuestionsResponse,
    OverallAnalytics,
    PageMeta,
    QuestionAnalytics,
    QuestionAnalyticsPage,
    QuestionAnalyticsResponse,
    QuestionFlagSummary,
    WrongAnswerSummary,
)
from app.modules.analytics.domain.enums import (
    AnalyticsScope,
    AssessmentType,
    AttemptStatus,
    DataState,
    FlagReason,
    FlagStatus,
    QuestionSortField,
    ReportingQuestionType,
    ReviewActionType,
    SortDirection,
)
from app.modules.analytics.domain.filters import AnalyticsFilters
from app.modules.analytics.domain.records import (
    AttemptRecord,
    Page,
    PageRequest,
    QuestionFlagRecord,
    QuestionMetadata,
    ResponseRecord,
    ReviewActionRecord,
)
from app.modules.analytics.domain.review import (
    ReviewActionRequest,
    ReviewActionResponse,
    ReviewAuditPage,
    ReviewHistoryResponse,
)

__all__ = [
    "AnalyticsFilters",
    "AnalyticsScope",
    "AssessmentType",
    "AttemptRecord",
    "AttemptStatus",
    "DataState",
    "FlagEvaluationResult",
    "FlagReason",
    "FlagStatus",
    "FlaggedQuestionsResponse",
    "OverallAnalytics",
    "Page",
    "PageMeta",
    "PageRequest",
    "QuestionAnalytics",
    "QuestionAnalyticsPage",
    "QuestionAnalyticsResponse",
    "QuestionFlagRecord",
    "QuestionFlagSummary",
    "QuestionMetadata",
    "QuestionSortField",
    "ReportingQuestionType",
    "ResponseRecord",
    "ReviewActionRecord",
    "ReviewActionRequest",
    "ReviewActionResponse",
    "ReviewActionType",
    "ReviewAuditPage",
    "ReviewHistoryResponse",
    "SortDirection",
    "WrongAnswerSummary",
]
