"""uc07 ai coaching review mode schema

Adds UC-07's four ``qk_*`` tables: the coaching session, its conversation, the knowledge-gap record
and the coaching activity stream.

Hand-adjusted after autogeneration to add the **append-only triggers**, which autogenerate does not
see: they are attached to SQLAlchemy ``after_create`` events, so a ``create_all`` database has them
and a migrated one would not. The DDL is imported from the models rather than copied, so there is
exactly one definition of each trigger and ``tests/test_schema_migration.py`` compares the two
schemas.

They are created at the very end of ``upgrade``, for the reason the previous revision records:
SQLite's ``batch_alter_table`` rebuilds a table, and a rebuild silently drops the triggers on it — so
no batch operation may follow their creation.

Revision ID: 0220750416ac
Revises: 2839992033cb
Create Date: 2026-08-19 20:59:00.000000
"""
from __future__ import annotations

import sys
from pathlib import Path
from typing import Sequence, Union

from alembic import op

import sqlalchemy as sa

BACKEND_DIR = Path(__file__).resolve().parents[2]
if str(BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(BACKEND_DIR))

# Autogenerate renders the custom timestamp type by its full path, so it must be importable here.
import app.db.types  # noqa: E402, F401
from app.modules.coaching import models as coaching_models  # noqa: E402

#: Every module contributing triggers in this revision.
TRIGGER_MODULES = (coaching_models,)

#: PostgreSQL trigger functions this revision creates, dropped again on downgrade.
POSTGRES_FUNCTIONS = (
    "fn_reject_coaching_message_update",
    "fn_reject_coaching_activity_update",
)


def _create_triggers() -> None:
    dialect = op.get_bind().dialect.name
    for module in TRIGGER_MODULES:
        if dialect == "sqlite":
            statements = module.sqlite_trigger_statements()
        elif dialect == "postgresql":
            statements = module.postgres_trigger_statements()
        else:
            # Another backend can still run the migration; the guarantees are also enforced by the
            # repository layer, and the trigger DDL for that dialect belongs in its own revision.
            return
        for statement in statements:
            op.execute(statement)


def _drop_triggers() -> None:
    dialect = op.get_bind().dialect.name
    if dialect not in {"sqlite", "postgresql"}:
        return
    for module in TRIGGER_MODULES:
        for name in module.trigger_names():
            if dialect == "sqlite":
                op.execute(f"DROP TRIGGER IF EXISTS {name}")
            else:
                op.execute(f"DROP TRIGGER IF EXISTS {name} ON {module.trigger_table(name)}")
    if dialect == "postgresql":
        for function in POSTGRES_FUNCTIONS:
            op.execute(f"DROP FUNCTION IF EXISTS {function}()")


revision: str = '0220750416ac'
down_revision: Union[str, None] = '2839992033cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qk_coaching_activity',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('learner_id', sa.String(length=64), nullable=False),
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=64), nullable=False),
    sa.Column('course_id', sa.String(length=64), nullable=True),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('mode', sa.String(length=24), nullable=True),
    sa.Column('exchange_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('failure_code', sa.String(length=64), nullable=True),
    sa.Column('occurred_at', app.db.types.UtcDateTime(timezone=True), nullable=False),
    sa.Column('created_at', app.db.types.UtcDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("event_type IN ('SESSION_STARTED', 'EXCHANGE_COMPLETED', 'DIRECT_EXPLANATION_OFFERED', 'MODE_CHANGED', 'SESSION_COMPLETED', 'SESSION_FAILED', 'SESSION_RETRIED')", name=op.f('ck_qk_coaching_activity_event_type')),
    sa.CheckConstraint("mode IS NULL OR mode IN ('SOCRATIC', 'DIRECT_EXPLANATION')", name=op.f('ck_qk_coaching_activity_mode')),
    sa.CheckConstraint("status IS NULL OR status IN ('ACTIVE', 'COMPLETED', 'FAILED', 'UNAVAILABLE')", name=op.f('ck_qk_coaching_activity_status')),
    sa.CheckConstraint('exchange_count >= 0', name=op.f('ck_qk_coaching_activity_exchange_count_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qk_coaching_activity'))
    )
    with op.batch_alter_table('qk_coaching_activity', schema=None) as batch_op:
        batch_op.create_index('ix_qk_coaching_activity_event_type', ['event_type'], unique=False)
        batch_op.create_index('ix_qk_coaching_activity_learner_attempt', ['learner_id', 'attempt_id'], unique=False)
        batch_op.create_index('ix_qk_coaching_activity_session_id', ['session_id'], unique=False)

    op.create_table('qk_coaching_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('learner_id', sa.String(length=64), nullable=False),
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=64), nullable=False),
    sa.Column('question_id', sa.String(length=64), nullable=False),
    sa.Column('question_position', sa.Integer(), nullable=True),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('mode', sa.String(length=24), nullable=False),
    sa.Column('exchange_count', sa.Integer(), nullable=False),
    sa.Column('direct_explanation_threshold', sa.Integer(), nullable=False),
    sa.Column('direct_explanation_offered', sa.Boolean(), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('last_failure_code', sa.String(length=64), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('started_at', app.db.types.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.types.UtcDateTime(timezone=True), nullable=False),
    sa.Column('completed_at', app.db.types.UtcDateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(status = 'COMPLETED') = (completed_at IS NOT NULL)", name=op.f('ck_qk_coaching_sessions_completed_state')),
    sa.CheckConstraint("mode IN ('SOCRATIC', 'DIRECT_EXPLANATION')", name=op.f('ck_qk_coaching_sessions_mode')),
    sa.CheckConstraint("status IN ('ACTIVE', 'COMPLETED', 'FAILED', 'UNAVAILABLE')", name=op.f('ck_qk_coaching_sessions_status')),
    sa.CheckConstraint('consecutive_failures >= 0', name=op.f('ck_qk_coaching_sessions_consecutive_failures_non_negative')),
    sa.CheckConstraint('direct_explanation_offered IN (0, 1)', name=op.f('ck_qk_coaching_sessions_direct_explanation_offered')),
    sa.CheckConstraint('direct_explanation_threshold >= 1', name=op.f('ck_qk_coaching_sessions_direct_explanation_threshold_positive')),
    sa.CheckConstraint('exchange_count >= 0', name=op.f('ck_qk_coaching_sessions_exchange_count_non_negative')),
    sa.CheckConstraint('question_position IS NULL OR question_position >= 1', name=op.f('ck_qk_coaching_sessions_position')),
    sa.CheckConstraint('revision >= 1', name=op.f('ck_qk_coaching_sessions_revision_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qk_coaching_sessions')),
    sa.UniqueConstraint('learner_id', 'attempt_id', 'question_id', name='natural_key')
    )
    with op.batch_alter_table('qk_coaching_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_qk_coaching_sessions_learner_attempt', ['learner_id', 'attempt_id'], unique=False)
        batch_op.create_index('ix_qk_coaching_sessions_status', ['status'], unique=False)

    op.create_table('qk_knowledge_gaps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('learner_id', sa.String(length=64), nullable=False),
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=64), nullable=False),
    sa.Column('question_id', sa.String(length=64), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=48), nullable=False),
    sa.Column('occurred_at', app.db.types.UtcDateTime(timezone=True), nullable=False),
    sa.Column('created_at', app.db.types.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qk_knowledge_gaps')),
    sa.UniqueConstraint('session_id', name='session_id')
    )
    with op.batch_alter_table('qk_knowledge_gaps', schema=None) as batch_op:
        batch_op.create_index('ix_qk_knowledge_gaps_learner_course', ['learner_id', 'course_id'], unique=False)
        batch_op.create_index('ix_qk_knowledge_gaps_topic', ['topic'], unique=False)

    op.create_table('qk_coaching_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('message_index', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('mode', sa.String(length=24), nullable=True),
    sa.Column('created_at', app.db.types.UtcDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("mode IS NULL OR mode IN ('SOCRATIC', 'DIRECT_EXPLANATION')", name=op.f('ck_qk_coaching_messages_mode')),
    sa.CheckConstraint("role IN ('LEARNER', 'COACH')", name=op.f('ck_qk_coaching_messages_role')),
    sa.CheckConstraint('message_index >= 0', name=op.f('ck_qk_coaching_messages_message_index_non_negative')),
    sa.ForeignKeyConstraint(['session_id'], ['qk_coaching_sessions.id'], name=op.f('fk_qk_coaching_messages_session_id_qk_coaching_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qk_coaching_messages')),
    sa.UniqueConstraint('session_id', 'message_index', name='session_id_message_index')
    )
    with op.batch_alter_table('qk_coaching_messages', schema=None) as batch_op:
        batch_op.create_index('ix_qk_coaching_messages_session_id', ['session_id'], unique=False)

    # ### end Alembic commands ###

    # LAST: no batch_alter_table may follow, or SQLite's table rebuild would drop these.
    _create_triggers()


def downgrade() -> None:
    # Triggers first: PostgreSQL needs them (and their functions) gone before the tables, and
    # being explicit on both backends keeps the two paths identical.
    _drop_triggers()

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qk_coaching_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_qk_coaching_messages_session_id')

    op.drop_table('qk_coaching_messages')
    with op.batch_alter_table('qk_knowledge_gaps', schema=None) as batch_op:
        batch_op.drop_index('ix_qk_knowledge_gaps_topic')
        batch_op.drop_index('ix_qk_knowledge_gaps_learner_course')

    op.drop_table('qk_knowledge_gaps')
    with op.batch_alter_table('qk_coaching_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_qk_coaching_sessions_status')
        batch_op.drop_index('ix_qk_coaching_sessions_learner_attempt')

    op.drop_table('qk_coaching_sessions')
    with op.batch_alter_table('qk_coaching_activity', schema=None) as batch_op:
        batch_op.drop_index('ix_qk_coaching_activity_session_id')
        batch_op.drop_index('ix_qk_coaching_activity_learner_attempt')
        batch_op.drop_index('ix_qk_coaching_activity_event_type')

    op.drop_table('qk_coaching_activity')
    # ### end Alembic commands ###
