"""uc10 analytics schema and cohort

Adds UC-10's two ``qy_*`` tables — the content-review flags and the append-only record of review
actions — plus the one additive column UC-10's cohort filter needs on the platform's enrolment
placeholder.

Hand-adjusted after autogeneration in one place: the **append-only triggers** on
``qy_review_actions``. Autogenerate cannot see them — they are attached to SQLAlchemy
``after_create`` events, so a ``create_all`` database has them and a migrated one would not. The
DDL is imported from the models rather than copied, so there is exactly one definition of each
trigger and ``tests/test_schema_migration.py`` compares the two schemas.

They are created at the very end of ``upgrade``, for the reason earlier revisions record: SQLite's
``batch_alter_table`` rebuilds a table, and a rebuild silently drops the triggers on it — so no
batch operation may follow their creation.

Revision ID: 050128fbddef
Revises: 108e83e56e69
Create Date: 2026-08-20 12:08:57.099311
"""
from __future__ import annotations

import sys
from pathlib import Path
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

BACKEND_DIR = Path(__file__).resolve().parents[2]
if str(BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(BACKEND_DIR))

# Autogenerate renders the custom timestamp type by its full path, so it must be importable here.
import app.db.types  # noqa: E402, F401
from app.modules.analytics import models as analytics_models  # noqa: E402

#: PostgreSQL trigger functions this revision creates, dropped again on downgrade.
POSTGRES_FUNCTIONS = ("fn_reject_qy_review_action_change",)


def _create_triggers() -> None:
    dialect = op.get_bind().dialect.name
    statements = (
        analytics_models.sqlite_trigger_statements()
        if dialect == "sqlite"
        else analytics_models.postgres_trigger_statements()
        if dialect == "postgresql"
        else ()
    )
    for statement in statements:
        op.execute(statement)


def _drop_triggers() -> None:
    dialect = op.get_bind().dialect.name
    for name in analytics_models.trigger_names():
        op.execute(f"DROP TRIGGER IF EXISTS {name}")
    if dialect == "postgresql":
        for function in POSTGRES_FUNCTIONS:
            op.execute(f"DROP FUNCTION IF EXISTS {function}() CASCADE")


revision: str = '050128fbddef'
down_revision: Union[str, None] = '108e83e56e69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qy_question_flags',
    sa.Column('question_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('wrong_answer_rate', sa.Float(), nullable=True),
    sa.Column('threshold_used', sa.Float(), nullable=True),
    sa.Column('graded_responses_at_flag', sa.Integer(), nullable=True),
    sa.Column('flagged_at', app.db.types.UtcDateTime(timezone=True), nullable=False),
    sa.Column('flagged_by', sa.String(length=128), nullable=False),
    sa.Column('resolved_at', app.db.types.UtcDateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=128), nullable=True),
    sa.Column('resolution_action', sa.String(length=32), nullable=True),
    sa.Column('updated_at', app.db.types.UtcDateTime(timezone=True), nullable=True),
    sa.CheckConstraint("reason IN ('WRONG_ANSWER_RATE_EXCEEDED', 'ADMINISTRATIVE_ACTION')", name=op.f('ck_qy_question_flags_ck_flag_reason')),
    sa.CheckConstraint("resolution_action IS NULL OR resolution_action IN ('NO_CHANGE', 'QUESTION_UPDATED', 'QUESTION_RETIRED')", name=op.f('ck_qy_question_flags_ck_flag_resolution_action')),
    sa.CheckConstraint("status IN ('FLAGGED', 'RESOLVED', 'RETIRED')", name=op.f('ck_qy_question_flags_ck_flag_status')),
    sa.CheckConstraint('(resolved_at IS NULL AND resolved_by IS NULL) OR (resolved_at IS NOT NULL AND resolved_by IS NOT NULL)', name=op.f('ck_qy_question_flags_ck_flag_resolution_attribution')),
    sa.CheckConstraint('graded_responses_at_flag IS NULL OR graded_responses_at_flag >= 0', name=op.f('ck_qy_question_flags_ck_flag_responses')),
    sa.CheckConstraint('wrong_answer_rate IS NULL OR (wrong_answer_rate >= 0 AND wrong_answer_rate <= 100)', name=op.f('ck_qy_question_flags_ck_flag_rate_range')),
    sa.PrimaryKeyConstraint('question_id', name=op.f('pk_qy_question_flags'))
    )
    with op.batch_alter_table('qy_question_flags', schema=None) as batch_op:
        batch_op.create_index('ix_flag_status', ['status', 'flagged_at'], unique=False)

    op.create_table('qy_review_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('admin_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', app.db.types.UtcDateTime(timezone=True), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('previous_flag_status', sa.String(length=24), nullable=True),
    sa.Column('resulting_flag_status', sa.String(length=24), nullable=True),
    sa.CheckConstraint("action IN ('NO_CHANGE', 'QUESTION_UPDATED', 'QUESTION_RETIRED')", name=op.f('ck_qy_review_actions_ck_action_type')),
    sa.CheckConstraint("previous_flag_status IS NULL OR previous_flag_status IN ('FLAGGED', 'RESOLVED', 'RETIRED')", name=op.f('ck_qy_review_actions_ck_action_previous_status')),
    sa.CheckConstraint("resulting_flag_status IS NULL OR resulting_flag_status IN ('FLAGGED', 'RESOLVED', 'RETIRED')", name=op.f('ck_qy_review_actions_ck_action_resulting_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qy_review_actions'))
    )
    with op.batch_alter_table('qy_review_actions', schema=None) as batch_op:
        batch_op.create_index('ix_action_admin', ['admin_id', 'created_at'], unique=False)
        batch_op.create_index('ix_action_question', ['question_id', 'created_at'], unique=False)

    with op.batch_alter_table('qa_enrolments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cohort_id', sa.String(length=128), nullable=True))
        batch_op.create_index('ix_qa_enrolments_cohort', ['course_id', 'cohort_id'], unique=False)

    # Hand-written: the append-only guard on the audit table, which autogenerate cannot see.
    # Last, because a later batch_alter_table would rebuild the table and drop them.
    _create_triggers()

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _drop_triggers()

    with op.batch_alter_table('qa_enrolments', schema=None) as batch_op:
        batch_op.drop_index('ix_qa_enrolments_cohort')
        batch_op.drop_column('cohort_id')

    with op.batch_alter_table('qy_review_actions', schema=None) as batch_op:
        batch_op.drop_index('ix_action_question')
        batch_op.drop_index('ix_action_admin')

    op.drop_table('qy_review_actions')
    with op.batch_alter_table('qy_question_flags', schema=None) as batch_op:
        batch_op.drop_index('ix_flag_status')

    op.drop_table('qy_question_flags')
    # ### end Alembic commands ###
