"""uc09 formal assessment schema

Revision ID: 108e83e56e69
Revises: c156bd33962a
Create Date: 2026-08-20 00:22:06.836707
"""
from __future__ import annotations

import sys
from pathlib import Path
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

BACKEND_DIR = Path(__file__).resolve().parents[2]
if str(BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(BACKEND_DIR))

# Autogenerate renders the custom timestamp type by its full path, so it must be importable here.
import app.db.types  # noqa: E402, F401


revision: str = '108e83e56e69'
down_revision: Union[str, None] = 'c156bd33962a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qs_formal_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('learner_id', sa.String(length=64), nullable=False),
    sa.Column('course_id', sa.String(length=64), nullable=False),
    sa.Column('quiz_id', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('attempt_id', sa.String(length=36), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=True),
    sa.Column('configuration_version_id', sa.String(length=64), nullable=True),
    sa.Column('retake_of_attempt_id', sa.String(length=36), nullable=True),
    sa.Column('conditions_version', sa.String(length=32), nullable=True),
    sa.Column('conditions_acknowledged_codes', sa.JSON(), nullable=True),
    sa.Column('conditions_acknowledged_at', app.db.types.UtcDateTime(timezone=True), nullable=True),
    sa.Column('conditions_user_agent', sa.Text(), nullable=True),
    sa.Column('identity_confirmed_at', app.db.types.UtcDateTime(timezone=True), nullable=True),
    sa.Column('identity_email_confirmed', sa.Boolean(), nullable=True),
    sa.Column('identity_email_supplied', sa.Boolean(), nullable=True),
    sa.Column('identity_rejected_attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('pending_identity_rejections', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('device_session_id', sa.String(length=36), nullable=True),
    sa.Column('started_at', app.db.types.UtcDateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', app.db.types.UtcDateTime(timezone=True), nullable=True),
    sa.Column('submission_reason', sa.String(length=32), nullable=True),
    sa.Column('disconnect_detected_at', app.db.types.UtcDateTime(timezone=True), nullable=True),
    sa.Column('disconnect_reported_by', sa.String(length=64), nullable=True),
    sa.Column('disconnect_last_seen_at', app.db.types.UtcDateTime(timezone=True), nullable=True),
    sa.Column('disconnect_autosaved_at', app.db.types.UtcDateTime(timezone=True), nullable=True),
    sa.Column('disconnect_answered_questions', sa.Integer(), nullable=True),
    sa.Column('disconnect_total_questions', sa.Integer(), nullable=True),
    sa.Column('disconnect_reason', sa.String(length=64), nullable=True),
    sa.Column('auto_submit_started_at', app.db.types.UtcDateTime(timezone=True), nullable=True),
    sa.Column('result_status', sa.String(length=24), nullable=True),
    sa.Column('result_passed', sa.Boolean(), nullable=True),
    sa.Column('result_percentage', sa.Float(), nullable=True),
    sa.Column('result_pass_mark', sa.Float(), nullable=True),
    sa.Column('result_total_marks', sa.Float(), nullable=True),
    sa.Column('result_maximum_marks', sa.Float(), nullable=True),
    sa.Column('result_score_status', sa.String(length=24), nullable=True),
    sa.Column('result_id', sa.String(length=36), nullable=True),
    sa.Column('result_calculated_at', app.db.types.UtcDateTime(timezone=True), nullable=True),
    sa.Column('review_id', sa.String(length=36), nullable=True),
    sa.Column('certificate_workflow_triggered_at', app.db.types.UtcDateTime(timezone=True), nullable=True),
    sa.Column('certificate_reference', sa.String(length=128), nullable=True),
    sa.Column('anomalies', sa.JSON(), nullable=True),
    sa.Column('created_at', app.db.types.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.types.UtcDateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("state IN ('NOT_STARTED', 'CONDITIONS_ACKNOWLEDGED', 'IDENTITY_CONFIRMED', 'ACTIVE', 'AUTO_SUBMIT_IN_PROGRESS', 'SUBMITTED', 'RESULT_CALCULATED', 'PASSED', 'FAILED', 'PENDING_REVIEW', 'APPROVED', 'REQUIRES_FURTHER_REVIEW', 'CERTIFICATE_ALLOWED')", name=op.f('ck_qs_formal_attempts_ck_formal_state')),
    sa.CheckConstraint("submission_reason IS NULL OR submission_reason IN ('LEARNER_CONFIRMED', 'TIME_EXPIRED', 'DISCONNECT_AUTO_SUBMIT')", name=op.f('ck_qs_formal_attempts_ck_formal_submission_reason')),
    sa.CheckConstraint('(submitted_at IS NULL AND submission_reason IS NULL) OR (submitted_at IS NOT NULL AND submission_reason IS NOT NULL)', name=op.f('ck_qs_formal_attempts_ck_formal_submission_pair')),
    sa.CheckConstraint('certificate_reference IS NULL OR certificate_workflow_triggered_at IS NOT NULL', name=op.f('ck_qs_formal_attempts_ck_formal_certificate_pair')),
    sa.CheckConstraint('identity_rejected_attempts >= 0', name=op.f('ck_qs_formal_attempts_ck_formal_identity_rejections')),
    sa.CheckConstraint('pending_identity_rejections >= 0', name=op.f('ck_qs_formal_attempts_ck_formal_pending_rejections')),
    sa.CheckConstraint('version >= 1', name=op.f('ck_qs_formal_attempts_ck_formal_version')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qs_formal_attempts'))
    )
    with op.batch_alter_table('qs_formal_attempts', schema=None) as batch_op:
        batch_op.create_index('ix_formal_attempt_learner_state', ['learner_id', 'state'], unique=False)
        batch_op.create_index('ix_formal_attempt_quiz', ['quiz_id', 'state'], unique=False)
        batch_op.create_index('ux_formal_attempt_idempotency', ['idempotency_key'], unique=True)
        batch_op.create_index('ux_formal_attempt_open', ['learner_id', 'quiz_id'], unique=True, sqlite_where=sa.text("state IN ('ACTIVE', 'AUTO_SUBMIT_IN_PROGRESS', 'CONDITIONS_ACKNOWLEDGED', 'IDENTITY_CONFIRMED')"), postgresql_where=sa.text("state IN ('ACTIVE', 'AUTO_SUBMIT_IN_PROGRESS', 'CONDITIONS_ACKNOWLEDGED', 'IDENTITY_CONFIRMED')"))
        batch_op.create_index('ux_formal_attempt_upstream', ['attempt_id'], unique=True, sqlite_where=sa.text('attempt_id IS NOT NULL'), postgresql_where=sa.text('attempt_id IS NOT NULL'))

    op.create_table('qs_formal_device_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('formal_attempt_id', sa.String(length=36), nullable=False),
    sa.Column('learner_id', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('session_token', sa.String(length=128), nullable=False),
    sa.Column('registered_at', app.db.types.UtcDateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', app.db.types.UtcDateTime(timezone=True), nullable=True),
    sa.Column('closed_at', app.db.types.UtcDateTime(timezone=True), nullable=True),
    sa.Column('closed_reason', sa.String(length=64), nullable=True),
    sa.Column('superseded_by_session_id', sa.String(length=36), nullable=True),
    sa.Column('client_request_id', sa.String(length=128), nullable=True),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=True),
    sa.Column('device_user_agent', sa.Text(), nullable=True),
    sa.Column('device_ip_address', sa.String(length=64), nullable=True),
    sa.Column('device_platform', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("(state = 'ACTIVE' AND closed_at IS NULL) OR (state <> 'ACTIVE')", name=op.f('ck_qs_formal_device_sessions_ck_device_active_not_closed')),
    sa.CheckConstraint("state IN ('ACTIVE', 'CLOSED', 'DISCONNECTED', 'REJECTED')", name=op.f('ck_qs_formal_device_sessions_ck_device_state')),
    sa.CheckConstraint('version >= 1', name=op.f('ck_qs_formal_device_sessions_ck_device_version')),
    sa.ForeignKeyConstraint(['formal_attempt_id'], ['qs_formal_attempts.id'], name=op.f('fk_qs_formal_device_sessions_formal_attempt_id_qs_formal_attempts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qs_formal_device_sessions'))
    )
    with op.batch_alter_table('qs_formal_device_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_device_session_learner', ['learner_id', 'state'], unique=False)
        batch_op.create_index('ux_device_session_active', ['formal_attempt_id'], unique=True, sqlite_where=sa.text("state = 'ACTIVE'"), postgresql_where=sa.text("state = 'ACTIVE'"))
        batch_op.create_index('ux_device_session_request', ['formal_attempt_id', 'client_request_id'], unique=True, sqlite_where=sa.text('client_request_id IS NOT NULL'), postgresql_where=sa.text('client_request_id IS NOT NULL'))

    op.create_table('qs_formal_reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('formal_attempt_id', sa.String(length=36), nullable=False),
    sa.Column('learner_id', sa.String(length=64), nullable=False),
    sa.Column('course_id', sa.String(length=64), nullable=False),
    sa.Column('quiz_id', sa.String(length=64), nullable=False),
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('submitted_at', app.db.types.UtcDateTime(timezone=True), nullable=True),
    sa.Column('auto_submitted', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('anomaly_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('assigned_to', sa.String(length=128), nullable=True),
    sa.Column('review_started_at', app.db.types.UtcDateTime(timezone=True), nullable=True),
    sa.Column('decision', sa.String(length=32), nullable=True),
    sa.Column('decided_by', sa.String(length=128), nullable=True),
    sa.Column('decided_at', app.db.types.UtcDateTime(timezone=True), nullable=True),
    sa.Column('decision_notes', sa.Text(), nullable=True),
    sa.Column('publish_state', sa.String(length=16), nullable=False),
    sa.Column('publish_attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('published_at', app.db.types.UtcDateTime(timezone=True), nullable=True),
    sa.Column('last_publish_error', sa.Text(), nullable=True),
    sa.Column('last_publish_attempt_at', app.db.types.UtcDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.db.types.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.types.UtcDateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("decision IS NULL OR decision IN ('APPROVED', 'REQUIRES_FURTHER_REVIEW')", name=op.f('ck_qs_formal_reviews_ck_review_decision')),
    sa.CheckConstraint("publish_state IN ('PENDING', 'PUBLISHED', 'FAILED')", name=op.f('ck_qs_formal_reviews_ck_review_publish_state')),
    sa.CheckConstraint("state IN ('PENDING_REVIEW', 'IN_REVIEW', 'APPROVED', 'REQUIRES_FURTHER_REVIEW')", name=op.f('ck_qs_formal_reviews_ck_review_state')),
    sa.CheckConstraint('(decision IS NULL AND decided_by IS NULL AND decided_at IS NULL) OR (decision IS NOT NULL AND decided_by IS NOT NULL AND decided_at IS NOT NULL)', name=op.f('ck_qs_formal_reviews_ck_review_decision_attribution')),
    sa.CheckConstraint('anomaly_count >= 0', name=op.f('ck_qs_formal_reviews_ck_review_anomaly_count')),
    sa.CheckConstraint('publish_attempts >= 0', name=op.f('ck_qs_formal_reviews_ck_review_publish_attempts')),
    sa.CheckConstraint('version >= 1', name=op.f('ck_qs_formal_reviews_ck_review_version')),
    sa.ForeignKeyConstraint(['formal_attempt_id'], ['qs_formal_attempts.id'], name=op.f('fk_qs_formal_reviews_formal_attempt_id_qs_formal_attempts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qs_formal_reviews'))
    )
    with op.batch_alter_table('qs_formal_reviews', schema=None) as batch_op:
        batch_op.create_index('ix_formal_review_assignee', ['assigned_to', 'state'], unique=False)
        batch_op.create_index('ix_formal_review_pending', ['state', 'created_at'], unique=False)
        batch_op.create_index('ix_formal_review_publish', ['publish_state', 'created_at'], unique=False)
        batch_op.create_index('ux_formal_review_attempt', ['formal_attempt_id'], unique=True)

    with op.batch_alter_table('qc_configuration_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_formal_assessment', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('requires_human_review', sa.Boolean(), server_default=sa.text('1'), nullable=False))
        batch_op.add_column(sa.Column('requires_assessor_approval', sa.Boolean(), server_default=sa.text('1'), nullable=False))

    # Hand-written: Alembic does not compare CHECK constraints. UC-09 introduces the assessor
    # role, and a migrated database would otherwise refuse to store one while the models happily
    # created it — the exact drift tests/test_schema_migration.py exists to catch.
    with op.batch_alter_table("qa_users", schema=None) as batch_op:
        batch_op.drop_constraint("users_role", type_="check")
        batch_op.create_check_constraint("users_role", "role IN ('admin', 'learner', 'assessor')")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # An assessor account would fail this on the rebuild — correctly: downgrading past the
    # release that introduced the role is a data question, not a schema one.
    with op.batch_alter_table("qa_users", schema=None) as batch_op:
        batch_op.drop_constraint("users_role", type_="check")
        batch_op.create_check_constraint("users_role", "role IN ('admin', 'learner')")

    with op.batch_alter_table('qc_configuration_versions', schema=None) as batch_op:
        batch_op.drop_column('requires_assessor_approval')
        batch_op.drop_column('requires_human_review')
        batch_op.drop_column('is_formal_assessment')

    with op.batch_alter_table('qs_formal_reviews', schema=None) as batch_op:
        batch_op.drop_index('ux_formal_review_attempt')
        batch_op.drop_index('ix_formal_review_publish')
        batch_op.drop_index('ix_formal_review_pending')
        batch_op.drop_index('ix_formal_review_assignee')

    op.drop_table('qs_formal_reviews')
    with op.batch_alter_table('qs_formal_device_sessions', schema=None) as batch_op:
        batch_op.drop_index('ux_device_session_request', sqlite_where=sa.text('client_request_id IS NOT NULL'), postgresql_where=sa.text('client_request_id IS NOT NULL'))
        batch_op.drop_index('ux_device_session_active', sqlite_where=sa.text("state = 'ACTIVE'"), postgresql_where=sa.text("state = 'ACTIVE'"))
        batch_op.drop_index('ix_device_session_learner')

    op.drop_table('qs_formal_device_sessions')
    with op.batch_alter_table('qs_formal_attempts', schema=None) as batch_op:
        batch_op.drop_index('ux_formal_attempt_upstream', sqlite_where=sa.text('attempt_id IS NOT NULL'), postgresql_where=sa.text('attempt_id IS NOT NULL'))
        batch_op.drop_index('ux_formal_attempt_open', sqlite_where=sa.text("state IN ('ACTIVE', 'AUTO_SUBMIT_IN_PROGRESS', 'CONDITIONS_ACKNOWLEDGED', 'IDENTITY_CONFIRMED')"), postgresql_where=sa.text("state IN ('ACTIVE', 'AUTO_SUBMIT_IN_PROGRESS', 'CONDITIONS_ACKNOWLEDGED', 'IDENTITY_CONFIRMED')"))
        batch_op.drop_index('ux_formal_attempt_idempotency')
        batch_op.drop_index('ix_formal_attempt_quiz')
        batch_op.drop_index('ix_formal_attempt_learner_state')

    op.drop_table('qs_formal_attempts')
    # ### end Alembic commands ###
