"""initial question bank schema

Revision ID: 5ea5d718773d
Revises: 
Create Date: 2026-08-17 10:58:50.395158
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5ea5d718773d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qb_question_imports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('imported_rows', sa.Integer(), nullable=False),
    sa.Column('rejected_rows', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('imported_rows >= 0', name=op.f('ck_qb_question_imports_question_imports_imported_non_negative')),
    sa.CheckConstraint('rejected_rows >= 0', name=op.f('ck_qb_question_imports_question_imports_rejected_non_negative')),
    sa.CheckConstraint('total_rows >= 0', name=op.f('ck_qb_question_imports_question_imports_total_rows_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qb_question_imports'))
    )
    with op.batch_alter_table('qb_question_imports', schema=None) as batch_op:
        batch_op.create_index('ix_qb_question_imports_started_at', ['started_at'], unique=False)
        batch_op.create_index('ix_qb_question_imports_status', ['status'], unique=False)

    op.create_table('qb_sequences',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_qb_sequences'))
    )
    op.create_table('qb_topics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=96), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qb_topics')),
    sa.UniqueConstraint('name', name=op.f('uq_qb_topics_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_qb_topics_slug'))
    )
    with op.batch_alter_table('qb_topics', schema=None) as batch_op:
        batch_op.create_index('ix_qb_topics_is_active', ['is_active'], unique=False)

    op.create_table('qb_question_import_errors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('import_id', sa.String(length=36), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=128), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('raw_row', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['qb_question_imports.id'], name=op.f('fk_qb_question_import_errors_import_id_qb_question_imports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qb_question_import_errors'))
    )
    with op.batch_alter_table('qb_question_import_errors', schema=None) as batch_op:
        batch_op.create_index('ix_qb_question_import_errors_import_id', ['import_id'], unique=False)
        batch_op.create_index('ix_qb_question_import_errors_import_id_row_number', ['import_id', 'row_number'], unique=False)

    op.create_table('qb_questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=32), nullable=False),
    sa.Column('external_ref', sa.String(length=128), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('scenario_text', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=16), nullable=True),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('scoring_strategy', sa.String(length=40), nullable=False),
    sa.Column('penalty_per_incorrect', sa.Float(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retired_reason', sa.Text(), nullable=True),
    sa.Column('retired_by', sa.String(length=128), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('updated_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('import_id', sa.String(length=36), nullable=True),
    sa.Column('import_row_number', sa.Integer(), nullable=True),
    sa.CheckConstraint('penalty_per_incorrect >= 0', name=op.f('ck_qb_questions_questions_penalty_non_negative')),
    sa.CheckConstraint('points > 0', name=op.f('ck_qb_questions_questions_points_positive')),
    sa.CheckConstraint('version >= 1', name=op.f('ck_qb_questions_questions_version_positive')),
    sa.ForeignKeyConstraint(['import_id'], ['qb_question_imports.id'], name=op.f('fk_qb_questions_import_id_qb_question_imports'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qb_questions')),
    sa.UniqueConstraint('external_ref', name=op.f('uq_qb_questions_external_ref')),
    sa.UniqueConstraint('reference', name=op.f('uq_qb_questions_reference')),
    sa.UniqueConstraint('seq', name=op.f('uq_qb_questions_seq'))
    )
    with op.batch_alter_table('qb_questions', schema=None) as batch_op:
        batch_op.create_index('ix_qb_questions_content_hash', ['content_hash'], unique=False)
        batch_op.create_index('ix_qb_questions_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_qb_questions_import_id', ['import_id'], unique=False)
        batch_op.create_index('ix_qb_questions_status', ['status'], unique=False)
        batch_op.create_index('ix_qb_questions_status_type', ['status', 'type'], unique=False)
        batch_op.create_index('ix_qb_questions_type', ['type'], unique=False)

    op.create_table('qb_question_options',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('correct_position', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('correct_position IS NULL OR correct_position >= 1', name=op.f('ck_qb_question_options_question_options_correct_position_positive')),
    sa.CheckConstraint('position >= 1', name=op.f('ck_qb_question_options_question_options_position_positive')),
    sa.ForeignKeyConstraint(['question_id'], ['qb_questions.id'], name=op.f('fk_qb_question_options_question_id_qb_questions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qb_question_options')),
    sa.UniqueConstraint('question_id', 'correct_position', name='uq_question_options_question_id_correct_position'),
    sa.UniqueConstraint('question_id', 'label', name='uq_question_options_question_id_label'),
    sa.UniqueConstraint('question_id', 'position', name='uq_question_options_question_id_position')
    )
    with op.batch_alter_table('qb_question_options', schema=None) as batch_op:
        batch_op.create_index('ix_qb_question_options_question_id', ['question_id'], unique=False)

    op.create_table('qb_question_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('scenario_text', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('scoring_strategy', sa.String(length=40), nullable=False),
    sa.Column('penalty_per_incorrect', sa.Float(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['qb_questions.id'], name=op.f('fk_qb_question_snapshots_question_id_qb_questions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qb_question_snapshots')),
    sa.UniqueConstraint('question_id', 'version', name='uq_question_snapshots_question_id_version')
    )
    with op.batch_alter_table('qb_question_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_qb_question_snapshots_content_hash', ['content_hash'], unique=False)
        batch_op.create_index('ix_qb_question_snapshots_question_id', ['question_id'], unique=False)

    op.create_table('qb_question_topics',
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('assigned_by', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['qb_questions.id'], name=op.f('fk_qb_question_topics_question_id_qb_questions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['qb_topics.id'], name=op.f('fk_qb_question_topics_topic_id_qb_topics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id', 'topic_id', name=op.f('pk_qb_question_topics'))
    )
    with op.batch_alter_table('qb_question_topics', schema=None) as batch_op:
        batch_op.create_index('ix_qb_question_topics_topic_id', ['topic_id'], unique=False)

    op.create_table('qb_question_usages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('attempt_ref', sa.String(length=128), nullable=False),
    sa.Column('learner_ref', sa.String(length=128), nullable=True),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_version', sa.Integer(), nullable=False),
    sa.Column('attempt_status', sa.String(length=16), nullable=False),
    sa.Column('learner_response', sa.Text(), nullable=True),
    sa.Column('presentation_order', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('awarded_points', sa.Float(), nullable=True),
    sa.Column('max_points', sa.Float(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['qb_questions.id'], name=op.f('fk_qb_question_usages_question_id_qb_questions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['qb_question_snapshots.id'], name=op.f('fk_qb_question_usages_snapshot_id_qb_question_snapshots'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qb_question_usages')),
    sa.UniqueConstraint('attempt_ref', 'question_id', name='uq_question_usages_attempt_ref_question_id')
    )
    with op.batch_alter_table('qb_question_usages', schema=None) as batch_op:
        batch_op.create_index('ix_qb_question_usages_attempt_ref', ['attempt_ref'], unique=False)
        batch_op.create_index('ix_qb_question_usages_attempt_status', ['attempt_status'], unique=False)
        batch_op.create_index('ix_qb_question_usages_question_id', ['question_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qb_question_usages', schema=None) as batch_op:
        batch_op.drop_index('ix_qb_question_usages_question_id')
        batch_op.drop_index('ix_qb_question_usages_attempt_status')
        batch_op.drop_index('ix_qb_question_usages_attempt_ref')

    op.drop_table('qb_question_usages')
    with op.batch_alter_table('qb_question_topics', schema=None) as batch_op:
        batch_op.drop_index('ix_qb_question_topics_topic_id')

    op.drop_table('qb_question_topics')
    with op.batch_alter_table('qb_question_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_qb_question_snapshots_question_id')
        batch_op.drop_index('ix_qb_question_snapshots_content_hash')

    op.drop_table('qb_question_snapshots')
    with op.batch_alter_table('qb_question_options', schema=None) as batch_op:
        batch_op.drop_index('ix_qb_question_options_question_id')

    op.drop_table('qb_question_options')
    with op.batch_alter_table('qb_questions', schema=None) as batch_op:
        batch_op.drop_index('ix_qb_questions_type')
        batch_op.drop_index('ix_qb_questions_status_type')
        batch_op.drop_index('ix_qb_questions_status')
        batch_op.drop_index('ix_qb_questions_import_id')
        batch_op.drop_index('ix_qb_questions_created_at')
        batch_op.drop_index('ix_qb_questions_content_hash')

    op.drop_table('qb_questions')
    with op.batch_alter_table('qb_question_import_errors', schema=None) as batch_op:
        batch_op.drop_index('ix_qb_question_import_errors_import_id_row_number')
        batch_op.drop_index('ix_qb_question_import_errors_import_id')

    op.drop_table('qb_question_import_errors')
    with op.batch_alter_table('qb_topics', schema=None) as batch_op:
        batch_op.drop_index('ix_qb_topics_is_active')

    op.drop_table('qb_topics')
    op.drop_table('qb_sequences')
    with op.batch_alter_table('qb_question_imports', schema=None) as batch_op:
        batch_op.drop_index('ix_qb_question_imports_status')
        batch_op.drop_index('ix_qb_question_imports_started_at')

    op.drop_table('qb_question_imports')
    # ### end Alembic commands ###
