"""uc08 retake management schema

Adds UC-08's two ``qt_*`` tables — the retake reservation and the additional-attempt grant — and
the two additive columns UC-08 and UC-09 need on UC-03's existing attempt row.

Hand-adjusted after autogeneration in two places, both of which autogenerate cannot see:

1. **``ck_attempt_reason`` is widened** to admit ``DISCONNECT_AUTO_SUBMIT``. Alembic does not
   compare CHECK constraints, so the model and a migrated database would silently disagree —
   ``tests/test_schema_migration.py`` is what catches that, and this is the fix. The value is
   UC-09's, and the constraint is widened here rather than there because ``qd_attempts`` is
   rebuilt by this revision anyway and rebuilding it twice on SQLite is avoidable churn.

2. **``import app.db.types``**, which the rendered ``UtcDateTime`` columns need and autogenerate
   omits.

``qd_attempts`` carries no triggers, so the SQLite table rebuild ``batch_alter_table`` performs
is safe here. That is checked rather than assumed: ``app/modules/attempt_delivery/models.py``
defines none, and the modules that do (UC-01, UC-04, UC-05, UC-06, UC-07) protect their own
tables, none of which this revision touches.

Revision ID: c156bd33962a
Revises: 0220750416ac
Create Date: 2026-08-19 23:42:18.109383
"""
from __future__ import annotations

import sys
from pathlib import Path
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

BACKEND_DIR = Path(__file__).resolve().parents[2]
if str(BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(BACKEND_DIR))

# Autogenerate renders the custom timestamp type by its full path, so it must be importable here.
import app.db.types  # noqa: E402, F401

#: The submission reasons a committed attempt may carry. ``DISCONNECT_AUTO_SUBMIT`` is UC-09's:
#: a formal assessment whose session drops is committed from the last valid autosaved state.
_SUBMISSION_REASONS = "'LEARNER_CONFIRMED', 'TIME_EXPIRED', 'DISCONNECT_AUTO_SUBMIT'"
_SUBMISSION_REASONS_BEFORE = "'LEARNER_CONFIRMED', 'TIME_EXPIRED'"


revision: str = 'c156bd33962a'
down_revision: Union[str, None] = '0220750416ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qt_additional_attempt_grants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('learner_id', sa.String(length=64), nullable=False),
    sa.Column('course_id', sa.String(length=64), nullable=False),
    sa.Column('quiz_id', sa.String(length=64), nullable=False),
    sa.Column('additional_attempts', sa.Integer(), nullable=False),
    sa.Column('granted_by', sa.String(length=128), nullable=False),
    sa.Column('granted_at', app.db.types.UtcDateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('revoked_at', app.db.types.UtcDateTime(timezone=True), nullable=True),
    sa.Column('revoked_by', sa.String(length=128), nullable=True),
    sa.CheckConstraint("(status = 'ACTIVE' AND revoked_at IS NULL AND revoked_by IS NULL) OR (status = 'REVOKED' AND revoked_at IS NOT NULL AND revoked_by IS NOT NULL)", name=op.f('ck_qt_additional_attempt_grants_ck_grant_revocation_state')),
    sa.CheckConstraint("status IN ('ACTIVE', 'REVOKED')", name=op.f('ck_qt_additional_attempt_grants_ck_grant_status')),
    sa.CheckConstraint('additional_attempts >= 1', name=op.f('ck_qt_additional_attempt_grants_ck_grant_additional_attempts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qt_additional_attempt_grants'))
    )
    with op.batch_alter_table('qt_additional_attempt_grants', schema=None) as batch_op:
        batch_op.create_index('ix_grant_scope', ['learner_id', 'course_id', 'quiz_id', 'status'], unique=False)
        batch_op.create_index('ux_grant_idempotency', ['idempotency_key'], unique=True)

    op.create_table('qt_retake_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('learner_id', sa.String(length=64), nullable=False),
    sa.Column('course_id', sa.String(length=64), nullable=False),
    sa.Column('quiz_id', sa.String(length=64), nullable=False),
    sa.Column('previous_attempt_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('configuration_version_id', sa.String(length=64), nullable=False),
    sa.Column('configuration_version_number', sa.Integer(), nullable=True),
    sa.Column('configuration_version_source', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempt_id', sa.String(length=36), nullable=True),
    sa.Column('requested_at', app.db.types.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.types.UtcDateTime(timezone=True), nullable=False),
    sa.Column('completed_at', app.db.types.UtcDateTime(timezone=True), nullable=True),
    sa.Column('question_plan', sa.JSON(), nullable=True),
    sa.Column('question_set_difference', sa.JSON(), nullable=True),
    sa.Column('anomalies', sa.JSON(), nullable=True),
    sa.Column('failure_code', sa.String(length=64), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("(status = 'COMPLETED' AND attempt_id IS NOT NULL AND completed_at IS NOT NULL) OR (status = 'RESERVED' AND attempt_id IS NULL) OR (status = 'FAILED')", name=op.f('ck_qt_retake_requests_ck_retake_completion_state')),
    sa.CheckConstraint("configuration_version_source IN ('CARRIED_FORWARD', 'ADVANCED_TO_ACTIVE', 'PINNED_TO_PREVIOUS')", name=op.f('ck_qt_retake_requests_ck_retake_version_source')),
    sa.CheckConstraint("status IN ('RESERVED', 'COMPLETED', 'FAILED')", name=op.f('ck_qt_retake_requests_ck_retake_status')),
    sa.CheckConstraint('attempt_count >= 1', name=op.f('ck_qt_retake_requests_ck_retake_attempt_count')),
    sa.CheckConstraint('attempt_number >= 1', name=op.f('ck_qt_retake_requests_ck_retake_attempt_number')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qt_retake_requests'))
    )
    with op.batch_alter_table('qt_retake_requests', schema=None) as batch_op:
        batch_op.create_index('ix_retake_attempt', ['attempt_id'], unique=False)
        batch_op.create_index('ix_retake_learner_quiz', ['learner_id', 'quiz_id', 'status'], unique=False)
        batch_op.create_index('ix_retake_previous_attempt', ['previous_attempt_id'], unique=False)
        batch_op.create_index('ux_retake_attempt_slot', ['learner_id', 'quiz_id', 'attempt_number'], unique=True, sqlite_where=sa.text("status <> 'FAILED'"), postgresql_where=sa.text("status <> 'FAILED'"))
        batch_op.create_index('ux_retake_idempotency', ['idempotency_key'], unique=True)

    with op.batch_alter_table('qd_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retake_of_attempt_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('is_formal_assessment', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        # Hand-written: autogenerate does not compare CHECK constraints. Dropped and recreated
        # rather than altered, because no backend can widen one in place.
        batch_op.drop_constraint('ck_attempt_reason', type_='check')
        batch_op.create_check_constraint(
            'ck_attempt_reason',
            f'submission_reason IS NULL OR submission_reason IN ({_SUBMISSION_REASONS})',
        )
        batch_op.create_index('ix_attempt_formal', ['quiz_id', 'is_formal_assessment'], unique=False)
        batch_op.create_index('ix_attempt_retake_of', ['retake_of_attempt_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qd_attempts', schema=None) as batch_op:
        batch_op.drop_index('ix_attempt_retake_of')
        batch_op.drop_index('ix_attempt_formal')
        # Narrowed back to the two reasons that existed before UC-09. An attempt already
        # committed with DISCONNECT_AUTO_SUBMIT would fail this on the rebuild — correctly:
        # downgrading past the release that can produce a value is a data question, not a
        # schema one, and it must surface rather than be silently rewritten.
        batch_op.drop_constraint('ck_attempt_reason', type_='check')
        batch_op.create_check_constraint(
            'ck_attempt_reason',
            f'submission_reason IS NULL OR submission_reason IN ({_SUBMISSION_REASONS_BEFORE})',
        )
        batch_op.drop_column('is_formal_assessment')
        batch_op.drop_column('retake_of_attempt_id')

    with op.batch_alter_table('qt_retake_requests', schema=None) as batch_op:
        batch_op.drop_index('ux_retake_idempotency')
        batch_op.drop_index('ux_retake_attempt_slot', sqlite_where=sa.text("status <> 'FAILED'"), postgresql_where=sa.text("status <> 'FAILED'"))
        batch_op.drop_index('ix_retake_previous_attempt')
        batch_op.drop_index('ix_retake_learner_quiz')
        batch_op.drop_index('ix_retake_attempt')

    op.drop_table('qt_retake_requests')
    with op.batch_alter_table('qt_additional_attempt_grants', schema=None) as batch_op:
        batch_op.drop_index('ux_grant_idempotency')
        batch_op.drop_index('ix_grant_scope')

    op.drop_table('qt_additional_attempt_grants')
    # ### end Alembic commands ###
