"""uc03 attempt delivery schema

Adds UC-03 (Quiz Attempt Delivery) and completes the hand-over of attempt ownership to it:

* ``qd_*`` — attempts, their frozen question set, answers, an append-only revision log, flags and
  submissions;
* ``qa_enrolments`` — the platform enrolment placeholder UC-03 checks before creating an attempt;
* three new ``qc_configuration_versions`` columns UC-03 reads: question presentation, option
  randomisation, and whether an incomplete submission is allowed;
* **drops ``qc_attempts``** and its version-locking trigger.

``qc_attempts`` was UC-01's provisional attempt table, written so "start quiz" could be demonstrated
before UC-03 existed. UC-03's model supersedes it entirely, so keeping both would have meant two
competing records of the same thing. UC-01 now reads the attempt counts its rules summary needs
through a read-only port. The three new columns carry ``server_default`` so they can be added to a
table that already has rows.

Hand-adjusted after autogeneration to drop the trigger created by the previous revision —
autogenerate does not see triggers.

Revision ID: f2edce6a1ae0
Revises: 998d713ed495
Create Date: 2026-08-18 19:29:14.758652
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op

# Autogenerate renders the custom column type by its full path, so it must be importable here.
import app.db.types  # noqa: F401
import sqlalchemy as sa


revision: str = 'f2edce6a1ae0'
down_revision: Union[str, None] = '998d713ed495'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


#: Created by revision 998d713ed495 on the table this revision drops.
ATTEMPT_LOCK_TRIGGER = "trg_qc_attempt_config_version_locked"


def _drop_attempt_lock_trigger() -> None:
    """Remove the version-locking trigger before its table goes.

    SQLite drops a table's triggers with it, but PostgreSQL needs the function dropped explicitly,
    and being explicit on both keeps the two paths identical.
    """
    dialect = op.get_bind().dialect.name
    if dialect == "sqlite":
        op.execute(f"DROP TRIGGER IF EXISTS {ATTEMPT_LOCK_TRIGGER}")
    elif dialect == "postgresql":
        op.execute(f"DROP TRIGGER IF EXISTS {ATTEMPT_LOCK_TRIGGER} ON qc_attempts")
        op.execute("DROP FUNCTION IF EXISTS fn_reject_attempt_version_change()")


def _create_attempt_lock_trigger() -> None:
    """Recreate it on downgrade, matching revision 998d713ed495."""
    dialect = op.get_bind().dialect.name
    if dialect == "sqlite":
        op.execute(
            f"""
CREATE TRIGGER {ATTEMPT_LOCK_TRIGGER}
BEFORE UPDATE OF configuration_version_id ON qc_attempts
WHEN NEW.configuration_version_id IS NOT OLD.configuration_version_id
BEGIN
  SELECT RAISE(ABORT, 'LOCKED_CONFIGURATION_VERSION: an attempt cannot change configuration version');
END;
"""
        )
    elif dialect == "postgresql":
        op.execute(
            """
CREATE OR REPLACE FUNCTION fn_reject_attempt_version_change()
RETURNS trigger AS $$
BEGIN
  IF NEW.configuration_version_id IS DISTINCT FROM OLD.configuration_version_id THEN
    RAISE EXCEPTION 'LOCKED_CONFIGURATION_VERSION: an attempt cannot change configuration version';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""
        )
        op.execute(
            f"""
CREATE TRIGGER {ATTEMPT_LOCK_TRIGGER}
BEFORE UPDATE ON qc_attempts
FOR EACH ROW EXECUTE FUNCTION fn_reject_attempt_version_change();
"""
        )


#: Created by revision 998d713ed495 on ``qc_configuration_versions``.
VERSION_IMMUTABILITY_TRIGGER = "trg_qc_config_version_no_update"

IMMUTABLE_MESSAGE = (
    "IMMUTABLE_CONFIGURATION_VERSION: configuration versions cannot be modified; "
    "create a new version instead"
)


def _recreate_version_immutability_trigger() -> None:
    """Reinstate the immutability trigger after altering ``qc_configuration_versions``.

    SQLite cannot add a column in place: Alembic's batch mode rebuilds the table and copies the
    rows, which **silently drops the table's triggers**. Without this, adding three columns would
    quietly remove the guarantee that a stored configuration version can never be edited — the
    single most important invariant UC-01 has, and one nothing else would have noticed was gone.

    PostgreSQL alters in place and keeps its triggers, so this is SQLite-only.
    """
    if op.get_bind().dialect.name != "sqlite":
        return
    op.execute(f"DROP TRIGGER IF EXISTS {VERSION_IMMUTABILITY_TRIGGER}")
    op.execute(
        f"""
CREATE TRIGGER {VERSION_IMMUTABILITY_TRIGGER}
BEFORE UPDATE ON qc_configuration_versions
BEGIN
  SELECT RAISE(ABORT, '{IMMUTABLE_MESSAGE}');
END;
"""
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qa_enrolments',
    sa.Column('learner_id', sa.String(length=128), nullable=False),
    sa.Column('course_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'COMPLETED', 'SUSPENDED', 'WITHDRAWN')", name=op.f('ck_qa_enrolments_enrolment_status')),
    sa.PrimaryKeyConstraint('learner_id', 'course_id', name=op.f('pk_qa_enrolments'))
    )
    with op.batch_alter_table('qa_enrolments', schema=None) as batch_op:
        batch_op.create_index('ix_qa_enrolments_course_id', ['course_id'], unique=False)

    op.create_table('qd_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('learner_id', sa.String(length=64), nullable=False),
    sa.Column('course_id', sa.String(length=64), nullable=False),
    sa.Column('quiz_id', sa.String(length=64), nullable=False),
    sa.Column('configuration_version_id', sa.String(length=64), nullable=False),
    sa.Column('configuration_version_number', sa.Integer(), nullable=False),
    sa.Column('configuration_snapshot', sa.JSON(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('question_presentation', sa.String(length=24), nullable=False),
    sa.Column('selection_seed', sa.String(length=64), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('current_position', sa.Integer(), nullable=False),
    sa.Column('time_limit_seconds', sa.Integer(), nullable=True),
    sa.Column('started_at', app.db.types.UtcDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', app.db.types.UtcDateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', app.db.types.UtcDateTime(timezone=True), nullable=True),
    sa.Column('finalised_at', app.db.types.UtcDateTime(timezone=True), nullable=True),
    sa.Column('submission_reason', sa.String(length=24), nullable=True),
    sa.Column('last_activity_at', app.db.types.UtcDateTime(timezone=True), nullable=False),
    sa.Column('created_at', app.db.types.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.types.UtcDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(status = 'ACTIVE' AND submitted_at IS NULL AND submission_reason IS NULL      AND finalised_at IS NULL) OR (status = 'SUBMISSION_PENDING' AND submitted_at IS NOT NULL      AND submission_reason IS NOT NULL AND finalised_at IS NULL) OR (status = 'SUBMITTED' AND submitted_at IS NOT NULL      AND submission_reason IS NOT NULL AND finalised_at IS NOT NULL)", name=op.f('ck_qd_attempts_ck_attempt_commit_state')),
    sa.CheckConstraint("question_presentation IN ('ONE_AT_A_TIME', 'ALL_AT_ONCE')", name=op.f('ck_qd_attempts_ck_attempt_question_presentation')),
    sa.CheckConstraint("status IN ('ACTIVE', 'SUBMISSION_PENDING', 'SUBMITTED')", name=op.f('ck_qd_attempts_ck_attempt_status')),
    sa.CheckConstraint("submission_reason IS NULL OR submission_reason IN ('LEARNER_CONFIRMED', 'TIME_EXPIRED')", name=op.f('ck_qd_attempts_ck_attempt_reason')),
    sa.CheckConstraint('(time_limit_seconds IS NULL AND expires_at IS NULL) OR (time_limit_seconds IS NOT NULL AND expires_at IS NOT NULL)', name=op.f('ck_qd_attempts_ck_attempt_expiry')),
    sa.CheckConstraint('attempt_number >= 1', name=op.f('ck_qd_attempts_ck_attempt_number')),
    sa.CheckConstraint('current_position >= 1', name=op.f('ck_qd_attempts_ck_attempt_current_position')),
    sa.CheckConstraint('time_limit_seconds IS NULL OR time_limit_seconds > 0', name=op.f('ck_qd_attempts_ck_attempt_time_limit')),
    sa.CheckConstraint('total_questions >= 0', name=op.f('ck_qd_attempts_ck_attempt_total_questions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qd_attempts')),
    sa.UniqueConstraint('learner_id', 'quiz_id', 'attempt_number', name='ux_attempt_number')
    )
    with op.batch_alter_table('qd_attempts', schema=None) as batch_op:
        batch_op.create_index('ix_attempt_config_version', ['configuration_version_id'], unique=False)
        batch_op.create_index('ix_attempt_expiry', ['status', 'expires_at'], unique=False)
        batch_op.create_index('ix_attempt_learner_course', ['learner_id', 'course_id'], unique=False)
        batch_op.create_index('ix_attempt_learner_quiz', ['learner_id', 'quiz_id', 'status'], unique=False)
        batch_op.create_index('ux_attempt_single_open', ['learner_id', 'quiz_id'], unique=True, sqlite_where=sa.text("status IN ('ACTIVE', 'SUBMISSION_PENDING')"), postgresql_where=sa.text("status IN ('ACTIVE', 'SUBMISSION_PENDING')"))

    op.create_table('qd_attempt_questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=64), nullable=False),
    sa.Column('question_version', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.String(length=24), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('question_snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', app.db.types.UtcDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("question_type IN ('SINGLE_CHOICE', 'TRUE_FALSE', 'MULTI_SELECT', 'SCENARIO', 'DRAG_TO_ORDER')", name=op.f('ck_qd_attempt_questions_ck_attempt_question_type')),
    sa.CheckConstraint('points >= 0', name=op.f('ck_qd_attempt_questions_ck_attempt_question_points')),
    sa.CheckConstraint('position >= 1', name=op.f('ck_qd_attempt_questions_ck_attempt_question_position')),
    sa.ForeignKeyConstraint(['attempt_id'], ['qd_attempts.id'], name=op.f('fk_qd_attempt_questions_attempt_id_qd_attempts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qd_attempt_questions')),
    sa.UniqueConstraint('attempt_id', 'position', name='ux_attempt_question_position'),
    sa.UniqueConstraint('attempt_id', 'question_id', name='ux_attempt_question_unique')
    )
    with op.batch_alter_table('qd_attempt_questions', schema=None) as batch_op:
        batch_op.create_index('ix_attempt_question_question', ['question_id'], unique=False)

    op.create_table('qd_attempt_submissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('submission_reason', sa.String(length=24), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('answered_count', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('response_snapshot', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('downstream_reference', sa.String(length=200), nullable=True),
    sa.Column('failure_code', sa.String(length=64), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.Column('requested_at', app.db.types.UtcDateTime(timezone=True), nullable=False),
    sa.Column('last_attempted_at', app.db.types.UtcDateTime(timezone=True), nullable=False),
    sa.Column('completed_at', app.db.types.UtcDateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(state = 'SUBMITTED') = (completed_at IS NOT NULL)", name=op.f('ck_qd_attempt_submissions_ck_submission_completed')),
    sa.CheckConstraint("state IN ('PENDING', 'SUBMITTED', 'FAILED')", name=op.f('ck_qd_attempt_submissions_ck_submission_state')),
    sa.CheckConstraint("submission_reason IN ('LEARNER_CONFIRMED', 'TIME_EXPIRED')", name=op.f('ck_qd_attempt_submissions_ck_submission_reason')),
    sa.CheckConstraint('answered_count >= 0 AND total_questions >= 0', name=op.f('ck_qd_attempt_submissions_ck_submission_counts')),
    sa.CheckConstraint('attempt_count >= 1', name=op.f('ck_qd_attempt_submissions_ck_submission_attempt_count')),
    sa.ForeignKeyConstraint(['attempt_id'], ['qd_attempts.id'], name=op.f('fk_qd_attempt_submissions_attempt_id_qd_attempts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qd_attempt_submissions')),
    sa.UniqueConstraint('attempt_id', 'idempotency_key', name='ux_submission_idempotency')
    )
    with op.batch_alter_table('qd_attempt_submissions', schema=None) as batch_op:
        batch_op.create_index('ix_submission_state', ['state', 'last_attempted_at'], unique=False)
        batch_op.create_index('ux_submission_single_success', ['attempt_id'], unique=True, sqlite_where=sa.text("state = 'SUBMITTED'"), postgresql_where=sa.text("state = 'SUBMITTED'"))

    op.create_table('qd_attempt_answer_revisions',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_question_id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('answered', sa.Boolean(), nullable=False),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.Column('response', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('saved_at', app.db.types.UtcDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("source IN ('MANUAL', 'AUTOSAVE', 'SYSTEM')", name=op.f('ck_qd_attempt_answer_revisions_ck_answer_revision_source')),
    sa.CheckConstraint('answered IN (TRUE, FALSE)', name=op.f('ck_qd_attempt_answer_revisions_ck_answer_revision_answered')),
    sa.ForeignKeyConstraint(['attempt_id'], ['qd_attempts.id'], name=op.f('fk_qd_attempt_answer_revisions_attempt_id_qd_attempts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['attempt_question_id'], ['qd_attempt_questions.id'], name=op.f('fk_qd_answer_revisions_attempt_question_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qd_attempt_answer_revisions')),
    sa.UniqueConstraint('attempt_question_id', 'revision', name='ux_answer_revision')
    )
    with op.batch_alter_table('qd_attempt_answer_revisions', schema=None) as batch_op:
        batch_op.create_index('ix_answer_revision_attempt', ['attempt_id', 'saved_at'], unique=False)

    op.create_table('qd_attempt_answers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_question_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=64), nullable=False),
    sa.Column('answered', sa.Boolean(), nullable=False),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.Column('response', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('response_hash', sa.String(length=64), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('first_saved_at', app.db.types.UtcDateTime(timezone=True), nullable=False),
    sa.Column('saved_at', app.db.types.UtcDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("source IN ('MANUAL', 'AUTOSAVE', 'SYSTEM')", name=op.f('ck_qd_attempt_answers_ck_answer_source')),
    sa.CheckConstraint('(answered AND response IS NOT NULL) OR (NOT answered AND response IS NULL)', name=op.f('ck_qd_attempt_answers_ck_answer_payload')),
    sa.CheckConstraint('answered IN (TRUE, FALSE)', name=op.f('ck_qd_attempt_answers_ck_answer_answered')),
    sa.CheckConstraint('complete IN (TRUE, FALSE) AND (NOT complete OR answered)', name=op.f('ck_qd_attempt_answers_ck_answer_complete')),
    sa.CheckConstraint('revision >= 1', name=op.f('ck_qd_attempt_answers_ck_answer_revision')),
    sa.ForeignKeyConstraint(['attempt_id'], ['qd_attempts.id'], name=op.f('fk_qd_attempt_answers_attempt_id_qd_attempts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['attempt_question_id'], ['qd_attempt_questions.id'], name=op.f('fk_qd_attempt_answers_attempt_question_id_qd_attempt_questions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qd_attempt_answers')),
    sa.UniqueConstraint('attempt_id', 'attempt_question_id', name='ux_answer_per_attempt_question'),
    sa.UniqueConstraint('attempt_id', 'question_id', name='ux_answer_per_question')
    )
    op.create_table('qd_attempt_question_flags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_question_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=64), nullable=False),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('flagged_at', app.db.types.UtcDateTime(timezone=True), nullable=True),
    sa.Column('updated_at', app.db.types.UtcDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('flagged = (flagged_at IS NOT NULL)', name=op.f('ck_qd_attempt_question_flags_ck_flag_instant')),
    sa.CheckConstraint('flagged IN (TRUE, FALSE)', name=op.f('ck_qd_attempt_question_flags_ck_flag_value')),
    sa.ForeignKeyConstraint(['attempt_id'], ['qd_attempts.id'], name=op.f('fk_qd_attempt_question_flags_attempt_id_qd_attempts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['attempt_question_id'], ['qd_attempt_questions.id'], name=op.f('fk_qd_question_flags_attempt_question_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qd_attempt_question_flags')),
    sa.UniqueConstraint('attempt_id', 'attempt_question_id', name='ux_flag_per_attempt_question')
    )
    with op.batch_alter_table('qd_attempt_question_flags', schema=None) as batch_op:
        batch_op.create_index('ix_flag_attempt_flagged', ['attempt_id', 'flagged'], unique=False)

    with op.batch_alter_table('qc_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qc_attempts_configuration_version_id'))
        batch_op.drop_index(batch_op.f('ix_qc_attempts_learner'))
        batch_op.drop_index(batch_op.f('ix_qc_attempts_one_in_progress'), sqlite_where=sa.text("status = 'in_progress'"))

    _drop_attempt_lock_trigger()
    op.drop_table('qc_attempts')
    with op.batch_alter_table('qc_configuration_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_presentation', sa.String(length=32), server_default='ALL_AT_ONCE', nullable=False))
        batch_op.add_column(sa.Column('randomise_option_order', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('allow_incomplete_submission', sa.Boolean(), server_default=sa.text('true'), nullable=False))
        # Autogenerate does not emit CHECK constraints for added columns. Without this, a migrated
        # database would accept a presentation value the models reject — and the drift test that
        # caught this is the only thing standing between that and production.
        batch_op.create_check_constraint(
            "question_presentation",
            "question_presentation IN ('ONE_AT_A_TIME', 'ALL_AT_ONCE')",
        )

    _recreate_version_immutability_trigger()

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qc_configuration_versions', schema=None) as batch_op:
        batch_op.drop_constraint("question_presentation", type_="check")
        batch_op.drop_column('allow_incomplete_submission')
        batch_op.drop_column('randomise_option_order')
        batch_op.drop_column('question_presentation')

    _recreate_version_immutability_trigger()

    op.create_table('qc_attempts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('quiz_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('configuration_version_id', sa.INTEGER(), nullable=False),
    sa.Column('attempt_number', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), nullable=False),
    sa.Column('usage_ref', sa.VARCHAR(length=128), nullable=False),
    sa.Column('started_at', sa.DATETIME(), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.Column('submitted_at', sa.DATETIME(), nullable=True),
    sa.Column('score_percent', sa.INTEGER(), nullable=True),
    sa.Column('passed', sa.BOOLEAN(), nullable=True),
    sa.CheckConstraint("status IN ('in_progress', 'submitted', 'abandoned')", name=op.f('ck_qc_attempts_status')),
    sa.CheckConstraint('attempt_number >= 1', name=op.f('ck_qc_attempts_attempt_number')),
    sa.CheckConstraint('score_percent IS NULL OR score_percent BETWEEN 0 AND 100', name=op.f('ck_qc_attempts_score_percent')),
    sa.ForeignKeyConstraint(['configuration_version_id'], ['qc_configuration_versions.id'], name=op.f('fk_qc_attempts_configuration_version_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['quiz_id'], ['qc_quizzes.id'], name=op.f('fk_qc_attempts_quiz_id_qc_quizzes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['qa_users.id'], name=op.f('fk_qc_attempts_user_id_qa_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qc_attempts')),
    sa.UniqueConstraint('quiz_id', 'user_id', 'attempt_number', name=op.f('quiz_id_user_id_attempt_number')),
    sa.UniqueConstraint('usage_ref', name=op.f('uq_qc_attempts_usage_ref'))
    )
    with op.batch_alter_table('qc_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qc_attempts_one_in_progress'), ['quiz_id', 'user_id'], unique=1, sqlite_where=sa.text("status = 'in_progress'"))
        batch_op.create_index(batch_op.f('ix_qc_attempts_learner'), ['quiz_id', 'user_id', 'attempt_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_qc_attempts_configuration_version_id'), ['configuration_version_id'], unique=False)

    # The table is back and indexed, so its guard can be reinstated.
    _create_attempt_lock_trigger()

    with op.batch_alter_table('qd_attempt_question_flags', schema=None) as batch_op:
        batch_op.drop_index('ix_flag_attempt_flagged')

    op.drop_table('qd_attempt_question_flags')
    op.drop_table('qd_attempt_answers')
    with op.batch_alter_table('qd_attempt_answer_revisions', schema=None) as batch_op:
        batch_op.drop_index('ix_answer_revision_attempt')

    op.drop_table('qd_attempt_answer_revisions')
    with op.batch_alter_table('qd_attempt_submissions', schema=None) as batch_op:
        batch_op.drop_index('ux_submission_single_success', sqlite_where=sa.text("state = 'SUBMITTED'"), postgresql_where=sa.text("state = 'SUBMITTED'"))
        batch_op.drop_index('ix_submission_state')

    op.drop_table('qd_attempt_submissions')
    with op.batch_alter_table('qd_attempt_questions', schema=None) as batch_op:
        batch_op.drop_index('ix_attempt_question_question')

    op.drop_table('qd_attempt_questions')
    with op.batch_alter_table('qd_attempts', schema=None) as batch_op:
        batch_op.drop_index('ux_attempt_single_open', sqlite_where=sa.text("status IN ('ACTIVE', 'SUBMISSION_PENDING')"), postgresql_where=sa.text("status IN ('ACTIVE', 'SUBMISSION_PENDING')"))
        batch_op.drop_index('ix_attempt_learner_quiz')
        batch_op.drop_index('ix_attempt_learner_course')
        batch_op.drop_index('ix_attempt_expiry')
        batch_op.drop_index('ix_attempt_config_version')

    op.drop_table('qd_attempts')
    with op.batch_alter_table('qa_enrolments', schema=None) as batch_op:
        batch_op.drop_index('ix_qa_enrolments_course_id')

    op.drop_table('qa_enrolments')
    # ### end Alembic commands ###
