"""Integration flows across the UC-01…UC-08 boundaries (§6, §8, §11, §12, §22).

These tests are about what UC-09 does *not* do. Each one asserts that a responsibility stayed where it already
lived:

* the learner's answers are UC-03's, written only through its autosave and submission;
* the score and the pass/fail decision are UC-04's and UC-05's, copied and never recalculated;
* the certificate is generated by UC-05's workflow, triggered only after approval;
* the notification goes out through the platform's channel;
* the audit trail goes into the platform's pipeline.

Everything is exercised through fakes bound at the composition root, so the same test runs against the real
modules once the company binds them.
"""

from __future__ import annotations

import pytest

from app.modules.formal_assessment.domain.enums import FormalAttemptState
from app.modules.formal_assessment.integration.uc03 import AnswerSubmission
from tests.formal_assessment.conftest import FormalFlow
from tests.formal_assessment.fakes import DEFAULT_ASSESSOR, DEFAULT_LEARNER

pytestmark = pytest.mark.anyio


async def test_the_whole_journey_from_conditions_to_certificate(
    flow: FormalFlow, container, passing, upstream, certificates, notifier, queue, audit
):
    """The lifecycle in §15, end to end, through the services."""
    acknowledged = await flow.acknowledge()
    assert acknowledged.state is FormalAttemptState.CONDITIONS_ACKNOWLEDGED

    confirmed = await flow.confirm_identity()
    assert confirmed.state is FormalAttemptState.IDENTITY_CONFIRMED

    started = await flow.start()
    assert started.formal_attempt.state is FormalAttemptState.ACTIVE

    await container.services.attempts.autosave(
        learner_id=DEFAULT_LEARNER,
        formal_attempt_id=flow.formal_attempt_id,
        session_token=flow.session_token,
        answers=tuple(
            AnswerSubmission(question_id=f"q{index}", response={"selectedOptionId": f"q{index}-o1"})
            for index in (1, 2, 3)
        ),
    )

    passing(flow.attempt_id)
    submitted = await flow.submit()
    assert submitted.formal_attempt.state is FormalAttemptState.PENDING_REVIEW

    review = await flow.review()
    assert review is not None
    outcome = await container.services.reviews.decide(
        assessor_id=DEFAULT_ASSESSOR, review_id=review.review_id, decision="APPROVED"
    )
    assert outcome.formal_attempt.state is FormalAttemptState.CERTIFICATE_ALLOWED

    # Each downstream system did its own part, exactly once.
    assert len(upstream.submissions) == 1
    assert certificates.certificate_count == 1
    assert notifier.events() == ["FORMAL_ASSESSMENT_APPROVED"]
    assert len(queue.keys()) == 1
    assert audit.count("FORMAL_ATTEMPT_STARTED") == 1
    assert audit.count("CERTIFICATE_WORKFLOW_TRIGGERED") == 1


async def test_uc09_stores_no_answers_of_its_own(flow: FormalFlow, container, upstream):
    """§6: the learner's answers live in UC-03 and nowhere else."""
    await flow.to_active()
    await container.services.attempts.autosave(
        learner_id=DEFAULT_LEARNER,
        formal_attempt_id=flow.formal_attempt_id,
        session_token=flow.session_token,
        answers=(AnswerSubmission(question_id="q1", response={"selectedOptionId": "q1-o2"}),),
    )
    record = await flow.record()
    rendered = str(record.as_dict())
    assert "q1-o2" not in rendered, "an answer must not be copied onto the formal record"
    assert upstream.attempts[flow.attempt_id].saved["q1"] == {"selectedOptionId": "q1-o2"}


async def test_the_autosave_payload_is_passed_through_unread(flow: FormalFlow, container, upstream):
    """UC-09 checks who is saving; UC-02/UC-03 own what a valid answer looks like."""
    await flow.to_active()
    exotic = {"orderedItemIds": ["i3", "i1", "i2"], "meta": {"anything": True}}
    await container.services.attempts.autosave(
        learner_id=DEFAULT_LEARNER,
        formal_attempt_id=flow.formal_attempt_id,
        session_token=flow.session_token,
        answers=(AnswerSubmission(question_id="q2", response=exotic),),
    )
    assert upstream.attempts[flow.attempt_id].saved["q2"] == exotic


async def test_uc09_never_recalculates_a_score(flow: FormalFlow, scores, results):
    """§8: even an implausible score is recorded as the engines reported it, not adjusted."""
    await flow.to_active()
    scores.record(flow.attempt_id, percentage=55.0, total_marks=5.5, maximum_marks=10.0)
    results.record(flow.attempt_id, status="PASSED", percentage=55.0, pass_mark=50.0)
    outcome = await flow.submit()

    result = outcome.formal_attempt.result
    assert result is not None
    assert result.passed is True, "UC-05 decided this; UC-09 does not second-guess it"
    assert result.percentage == 55.0
    assert result.pass_mark == 50.0


async def test_the_certificate_trigger_carries_the_approval_for_uc05(flow: FormalFlow, container, passing, certificates):
    """§11, §12: the workflow receives who approved it and when, on the request itself."""
    await flow.to_active()
    passing(flow.attempt_id)
    await flow.submit()
    review = await flow.review()
    assert review is not None
    await container.services.reviews.decide(
        assessor_id=DEFAULT_ASSESSOR, review_id=review.review_id, decision="APPROVED"
    )

    trigger = certificates.triggers[0]
    assert trigger.approved_by == DEFAULT_ASSESSOR
    assert trigger.approved_at
    assert trigger.review_id == review.review_id
    assert trigger.attempt_id == flow.attempt_id
    assert trigger.percentage == 90.0
    assert trigger.idempotency_key == f"formal-certificate:{flow.formal_attempt_id}"


async def test_the_notification_carries_no_contact_details(flow: FormalFlow, container, passing, notifier):
    """§12: the notifier resolves the channel from the learner id; UC-09 holds no second copy."""
    await flow.to_active()
    passing(flow.attempt_id)
    await flow.submit()
    review = await flow.review()
    assert review is not None
    await container.services.reviews.decide(
        assessor_id=DEFAULT_ASSESSOR, review_id=review.review_id, decision="APPROVED"
    )

    notification = notifier.sent[0]
    rendered = str(notification.as_dict())
    assert "john.smith@example.com" not in rendered
    assert notification.learner_id == DEFAULT_LEARNER
    assert notification.review_id == review.review_id


async def test_an_upstream_state_mismatch_is_flagged_rather_than_overwritten(flow: FormalFlow, container, upstream):
    """UC-03 owns the attempt; a disagreement is an observation for a human, not something to silently fix."""
    await flow.to_active()
    upstream.force_status(flow.attempt_id, "SUBMITTED")

    status = await container.services.attempts.status(DEFAULT_LEARNER, flow.formal_attempt_id)
    codes = {item.code.value for item in status.formal_attempt.anomalies}
    assert "UPSTREAM_STATE_MISMATCH" in codes
    assert status.formal_attempt.state is FormalAttemptState.ACTIVE, "UC-09 did not rewrite its own record"


async def test_a_transient_upstream_status_is_not_treated_as_a_mismatch(flow: FormalFlow, container, upstream):
    """SUBMISSION_PENDING is UC-03's own transient state on the way to SUBMITTED."""
    await flow.to_active()
    upstream.force_status(flow.attempt_id, "SUBMISSION_PENDING")
    status = await container.services.attempts.status(DEFAULT_LEARNER, flow.formal_attempt_id)
    codes = {item.code.value for item in status.formal_attempt.anomalies}
    assert "UPSTREAM_STATE_MISMATCH" not in codes


async def test_a_formal_retake_records_its_lineage(flow: FormalFlow, container, passing, upstream):
    """§8 of UC-08 meets UC-09: a formal retake is a new sitting that remembers what it follows."""
    await flow.to_active()
    passing(flow.attempt_id)
    await flow.submit()
    first_attempt_id = flow.attempt_id

    retake = FormalFlow(container=container)
    await retake.acknowledge()
    await retake.confirm_identity()
    outcome = await container.services.attempts.start(
        learner_id=DEFAULT_LEARNER,
        quiz_id=retake.quiz_id,
        retake_of_attempt_id=first_attempt_id,
    )
    assert outcome.formal_attempt.retake_of_attempt_id == first_attempt_id
    assert upstream.created[-1].retake_of_attempt_id == first_attempt_id
    assert outcome.formal_attempt.attempt_id != first_attempt_id


async def test_an_ordinary_quiz_is_untouched_by_uc09(container, policies):
    """UC-09 gates formal assessments. An ordinary quiz keeps every existing rule and none of these."""
    policies.publish("quiz-ordinary", formal=False)

    from app.modules.formal_assessment.domain.errors import QuizNotFormalAssessmentError

    with pytest.raises(QuizNotFormalAssessmentError):
        await container.services.conditions.describe("quiz-ordinary")

    # No formal record exists for an ordinary attempt, so the certificate gate has no opinion...
    eligibility = await container.services.certificates.check_eligibility_for_attempt("attempt-ordinary")
    assert eligibility.decision.value == "NOT_FORMAL_ASSESSMENT"

    # ...and coaching is unaffected.
    permission = await container.services.coaching.is_ai_coaching_allowed(
        learner_id=DEFAULT_LEARNER, attempt_id="attempt-ordinary"
    )
    assert permission.allowed is True


async def test_the_module_is_mounted_for_its_three_audiences():
    """§22: the integration points, as the merge left them.

    Standalone, UC-09 asserted one prefix and one ``app.state`` key. The merged application mounts
    the three halves under the three roots their audiences already use — a learner talks to
    ``/api/v1`` like every other learner-facing capability, an assessor to ``/api/assessor``, the
    platform to ``/api/system`` — because the three carry three different credentials and a route
    in the wrong group would be a route with the wrong guard. The single ``app.state`` key is
    unchanged.
    """
    from app.main import create_app
    from app.modules.formal_assessment.api.dependencies import CONTAINER_STATE_KEY

    assert CONTAINER_STATE_KEY == "formal_assessment"
    app = create_app()
    assert getattr(app.state, CONTAINER_STATE_KEY, None) is not None

    paths = set(app.openapi()["paths"])
    assert "/api/v1/quizzes/{quiz_id}/formal-conditions" in paths
    assert "/api/assessor/pending-reviews" in paths
    assert (
        "/api/system/formal-assessments/attempts/{attempt_id}/certificate-eligibility" in paths
    )


async def test_the_rules_never_reach_a_database_library():
    """§16, in the form the merge left true.

    Standalone this asserted zero database imports anywhere in UC-09, because the module owned no
    schema at all. The merged module owns three ``qs_`` tables and a SQLAlchemy binding for them,
    so the claim narrows to where it always mattered: a domain rule or a service that imported an
    ORM could no longer be reasoned about, or tested, without a database — and everything this
    suite asserts runs against the in-memory binding, which is the proof.

    ``models.py``, ``repositories/sqlalchemy.py``, the ``integration/*adapter*.py`` files and the
    composition root are outside the claim: an adapter's whole job is to hold a session.
    """
    import pathlib

    banned = ("sqlalchemy", "alembic", "psycopg", "asyncpg", "aiosqlite", "sqlite3", "pymysql")
    module_root = (
        pathlib.Path(__file__).resolve().parents[1] / "app" / "modules" / "formal_assessment"
    )
    database_free = ("domain", "services", "schemas", "api")

    offenders = []
    for path in module_root.rglob("*.py"):
        if "__pycache__" in path.parts:
            continue
        relative = path.relative_to(module_root)
        if relative.parts[0] not in database_free:
            continue
        text = path.read_text(encoding="utf-8").lower()
        for name in banned:
            if f"import {name}" in text or f"from {name}" in text:
                offenders.append((str(relative), name))
    assert offenders == []
